"""update field power_name in powers to be unique

Revision ID: 70304abc1840
Revises: 4d1e4e31ecc5
Create Date: 2025-07-07 12:43:53.511707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70304abc1840'
down_revision: Union[str, Sequence[str], None] = '4d1e4e31ecc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'powers', ['power_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'powers', type_='unique')
    # ### end Alembic commands ###
