"""delete heroes and villain tables and create a unique table characters

Revision ID: 7521df029292
Revises: 70304abc1840
Create Date: 2025-07-07 16:54:42.338992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7521df029292'
down_revision: Union[str, Sequence[str], None] = '70304abc1840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('character_type', sa.Enum('hero', 'villain', name='charactertype'), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.drop_index(op.f('ix_villain_evil_name'), table_name='villain')
    op.drop_table('villain')
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hero_pkey'))
    )
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=False)
    op.create_table('villain',
    sa.Column('evil_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('villain_pkey'))
    )
    op.create_index(op.f('ix_villain_evil_name'), 'villain', ['evil_name'], unique=False)
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
