"""add link table character_power and make relationships

Revision ID: ab5225db22cf
Revises: e5cef9dce4a6
Create Date: 2025-07-08 17:10:24.843821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5225db22cf'
down_revision: Union[str, Sequence[str], None] = 'e5cef9dce4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characterpower',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['powers.power_id'], ),
    sa.PrimaryKeyConstraint('character_id', 'power_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characterpower')
    # ### end Alembic commands ###
